### ISSUE TITLE
update when

### ISSUE THREAD

**Issue by coffee100percnt** [dexthcity/FloppaOS#4]
POCO X2 CAMERA FIX WHENN!!!!!! I AM SO ANGRY TO XIAOMI!!!!! I NEVER GO XIAOMI AGAIN 😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡 THEY DON'T FIX CAMERA!!!🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏XIAOMI PLEASE UPDATE OR I NEVER BUY ANY XIAOMI PHONE 📱 AGAIN

MI A3 UN-HARDBRICK UPDATE WHENN!!!!!! I AM SO ANGRY TO XIAOMI!!!!! I NEVER GO XIAOMI AGAIN 😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡 THEY DON'T FIX HARDBRICK!!!🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏XIAOMI PLEASE UPDATE OR I NEVER BUY ANY XIAOMI PHONE 📱 AGAIN

REDMI NOTE 9 AMOLED OTA WHENN!!!!!! I AM SO ANGRY TO XIAOMI!!!!! I NEVER GO XIAOMI AGAIN 😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡 THEY DON'T GIVE STUPID PHONE WITH LCD AND DON'T GIVE AMOLED OTA!!!🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏XIAOMI PLEASE UPDATE OR I NEVER BUY ANY XIAOMI PHONE 📱 AGAIN

MI A3 MUI 16.9 ANDROD 13 WHENNNNNNNNNNNN!!!!!!!!!!!!!!!!! I AM SO ANGRY TO XIOAMI!!!!! I NEVER GO XIAOMI AGAIN 😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡 THRY GIVE STUPID ANDROID ONE WHICH HAVE ZERO FEATURES AND TOTAL NONSENSE!!!!!!!!!!!!!!!! NOW WHEN PEOPLE WANT 🅱️IUI 16.9 ANDROID 13 THRY GIVR USELESS ANDROID ONE🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏XIAOMI PLEASE UPDATE OR I NEVER BUY ANY XAOIMI PHONE 📱 AGAINNN!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by discographi** [comment]
макинтош бизнес онли знаешь моё имя имя ниначто нинамекаю но со мною тима сквад)

**Comment by deviceesamp** [comment]
слыш **лошок** ты ещё раз повыебывайся тут на мою флоппаос я те по макушке _**половником**_ ебну. **_петух_**

**Comment by coffee100percnt** [comment]
пошел в попу

**Comment by 15baller** [comment]
Сука вы гандоны

**Comment by coffee100percnt** [comment]
закройся

**Comment by coffee100percnt** [comment]
іді нахуй
